/**
 * This file was generated by the JPA Modeler
 */
package com.asseco.lookups;

import com.asseco.model.*;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "CB_COUNTRY")
public class CbCountry extends AbstractEntity {


    @OneToMany(targetEntity = Organization.class, mappedBy = "country", fetch = FetchType.LAZY)
    private List<Organization> Organizationcollection;

    @Column(name = "LABEL", table = "CB_COUNTRY", length = 45)
    @Basic
    private String label;

    @Column(name = "MK_LABEL", table = "CB_COUNTRY", length = 45)
    @Basic
    private String mkLabel;

    @Column(name = "ISO", table = "CB_COUNTRY", length = 45)
    @Basic
    private String iso;

    @Column(name = "ISO3", table = "CB_COUNTRY", length = 45)
    @Basic
    private String iso3;

    @Column(name = "NUMCODE", table = "CB_COUNTRY")
    @Basic
    private Integer numcode;

    @OneToMany(mappedBy = "country", fetch = FetchType.LAZY)
    private List<Grad> gradovi;

    @Override
    public void genericSet(String attributeName, Object value) throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getSelectMenuLabel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setClassData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getMkLabel() {
        return mkLabel;
    }

    public void setMkLabel(String mkLabel) {
        this.mkLabel = mkLabel;
    }

    public String getIso() {
        return iso;
    }

    public void setIso(String iso) {
        this.iso = iso;
    }

    public String getIso3() {
        return iso3;
    }

    public void setIso3(String iso3) {
        this.iso3 = iso3;
    }

    public Integer getNumcode() {
        return numcode;
    }

    public void setNumcode(Integer numcode) {
        this.numcode = numcode;
    }

    public List<Grad> getGradovi() {
        return gradovi;
    }

    public void setGradovi(List<Grad> gradovi) {
        this.gradovi = gradovi;
    }

    public List<Organization> getOrganizationcollection() {
        return Organizationcollection;
    }

    public void setOrganizationcollection(List<Organization> organizationcollection) {
        Organizationcollection = organizationcollection;
    }
}
